---
language: node_js

node_js:
  - '11'
  - '6'

sudo: false

matrix:
  fast_finish: true

install:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1

script:
  - npm run test
  - npm run compile

after_success:
  - npm run coverage
